### PR TITLE
Various fixes for Hotfix 0.16.2

### PR DESCRIPTION
**Pull request by ey8ymia**
- astakos: Fix ASTAKOS_TWITTER_TOKEN variable name in config file
- docs : Update admin guide
- admin: Check usage to decide if resource is useful

### CODE REVIEW

**Comment by apyrgio** [comment]
LGTM

**Comment by apyrgio** [comment]
Regarding the latest commit (1afc19ffa3dc8bf7ea8a8755262ccb18a0194452) in this pull request, I concur that it is viable for merge.

**Comment by apyrgio** [comment]
LGTM

**Comment by psomas** [comment]
Merged

**Pull request closed without merging**
